### ISSUE TITLE
Sample Toolkit App link is broken in Readme.md

### ISSUE THREAD

**Issue by seansparkman** [FormsCommunityToolkit/FormsCommunityToolkit#29]
Bug
Here is the link:
https://github.com/FormsCommunityToolkit/FormsCommunityToolkit/blob/dev

Text:
Want to see the toolkit in action before jumping into the code? Download and play with the Forms Toolkit Sample App.

I would submit a pull request if I knew where the sample exists.  Is this a problem with permissions maybe?

**Comment by Depechie** [comment]
Good catch! We'll try to adjust this asap... keep you posted.

**Comment by bartlannoeye** [comment]
After moving all separate repositories into this one, we only migrated the code. We opted to leave the sample app behind because it was not a straight forward code merge. We're looking into the best approach to have a modular sample app. As soon as the baseline is ready, we'll update you so you can send in a PR.

**Comment by Abhijeet-Xamarin** [comment]
Is sample available on other link now ?

**Comment by dfoulk** [comment]
I'm also interested in a Sample App or documentation. I'm sure you're working on it, so I will wait patiently lol. Thanks!
